spring:
  profiles: prod
  datasource:
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password:
logging:
  config: classpath:logback-prod.xml
